# -*- coding: utf-8 -*-
"""
Created on Mon May  9 18:29:00 2022

@author: admin
"""


def NewCash(doc):
    NewCash_Emp= []

    NewCash_Emp.append({
        
        'SYS_ID':doc[0],
        'SYS_COMPANYID':doc[1],
        'TMP_DECCOMPANYID':doc[2],
        'TMP_DECCOMPANYNAME':doc[3],
        'TMP_DECCOMPANYENGNAME':doc[4],
        'DEPARTID':doc[5],
        'DEPARTID2':doc[6],
        'TMP_DEPARTNAME':doc[7],
        'TMP_DEPARTENGNAME':doc[8],
        'SERIAL':doc[9],
        'EMPLOYEEID2':doc[10],
        'EMPLOYEEID':doc[11],
        'EMPLOYEENAME':doc[12],
        'EMPLOYEEENGNAME':doc[13],
        'IDNO':doc[14],
        'JOBSTATUS':doc[15],
        'COUNTRYNAME':doc[16],
        'BIRTHDATE':doc[17],
        'SEX':doc[18],
        'MARRAGE':doc[19],
        'BLOODTYPE':doc[20],
        'BIRTHPLACE':doc[21],
        'OTHER_BIRTHPLACE':doc[22],
        'VTITLEDEPARTID':doc[23],
        'HDEGREE':doc[24],
        'ISTOP':doc[25],
        'STARTDATE':doc[26],
        'WORKINGYEARS':doc[27],
        'SSTARTDATE':doc[28],
        'SPECIALYEARS':doc[29],
        'GARRIVEDATE':doc[30],
        'MOIBLE':doc[31],
        'OFFICETEL1':doc[32],
        'OFFICETEL2':doc[33],
        'PSNEMAI':doc[34],
        'EMAIL1':doc[35],
        'EMAIL2':doc[36],
        'REGTEL':doc[37],
        'REGADDRESS':doc[38],
        'COMMTEL':doc[39],
        'COMMADDRESS':doc[40],
        'EMERGENCYNAME':doc[41],
        'EMERGENCYTELNO':doc[42],
        'EMERGENCYMOBILE':doc[43],
        'EMERGENCYSEX':doc[44],
        'TMP_EMERGENCYID':doc[45],
        'TMP_EMERGENCYNAME':doc[46],
        'JOBCODENAME':doc[47],
        'JOBCODEENGNAME':doc[48],
        'JOBLEVELNAME':doc[49],
        'JOBLEVELENGNAME':doc[50],
        'JOBRANKNAME':doc[51],
        'JOBRANKENGNAME':doc[52],
        'JOBCODEID':doc[53],
        'JOBLEVELID':doc[54],
        'JOBRANKID':doc[55],
        'GD1':doc[56],
        'GD2':doc[57],
        'GD3':doc[58],
        'GD4':doc[59],
        'GD5':doc[60],
        'GD6':doc[61],
        'GD1_ID':doc[62],
        'GD2_ID':doc[63],
        'SELFDEF1':doc[64],
        'SELFDEF2':doc[65],
        'SELFDEF3':doc[66],
        'SELFDEF4':doc[67],
        'SELFDEF5':doc[68],
        'TMP_PROFITID':doc[69],
        'TMP_PROFITNAME':doc[70],
        'TMP_IDYCLASSID':doc[71],
        'TMP_IDYCLASSNAME':doc[72],
        'ISDIRECT':doc[73],
        'ETHNICID':doc[74],
        'ISDISABILITY':doc[75],
        'DISABILITYDEGREE':doc[76],
        'NOTE':doc[77],
        'WORKINGYEARSYMD':doc[78],
        'SELFDEF6':doc[79],
        'SELFDEF7':doc[80],
        'SELFDEF8':doc[81],
        'JOBDESCRIPTION':doc[82],
        'JOBCONTRACT':doc[83],

    })
    return NewCash_Emp