# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class WbtCourtAuctionTbItem(scrapy.Item):
    rowid = scrapy.Field()
    court = scrapy.Field()
    number = scrapy.Field()
    date = scrapy.Field()
    country = scrapy.Field()
    address = scrapy.Field()
    reserve = scrapy.Field()
    price = scrapy.Field()
    handover = scrapy.Field()
    vacancy = scrapy.Field()
    target = scrapy.Field()
    remark = scrapy.Field()
    document = scrapy.Field()
    entrydate = scrapy.Field()
    court = scrapy.Field()
    number = scrapy.Field()
    unit = scrapy.Field()
    date = scrapy.Field()
    turn = scrapy.Field()
    country = scrapy.Field()
    town = scrapy.Field()
    address = scrapy.Field()
    area = scrapy.Field()
    reserve = scrapy.Field()
    price = scrapy.Field()
    remark = scrapy.Field()
    owner = scrapy.Field()
    entrydate = scrapy.Field()
    refertb = scrapy.Field()
    referi = scrapy.Field()
    parcel = scrapy.Field()

    date_datetime = scrapy.Field()
    saletype = scrapy.Field()
    proptype = scrapy.Field()
    reserve_int = scrapy.Field()
    type = scrapy.Field()


class AuctionInfoTbItem(scrapy.Item):
    rowid = scrapy.Field()
    court = scrapy.Field()
    number = scrapy.Field()
    date = scrapy.Field()
    country = scrapy.Field()
    address = scrapy.Field()
    reserve = scrapy.Field()
    price = scrapy.Field()
    handover = scrapy.Field()
    vacancy = scrapy.Field()
    target = scrapy.Field()
    remark = scrapy.Field()
    document = scrapy.Field()
    entrydate = scrapy.Field()
    court = scrapy.Field()
    number = scrapy.Field()
    unit = scrapy.Field()
    date = scrapy.Field()
    turn = scrapy.Field()
    country = scrapy.Field()
    town = scrapy.Field()
    address = scrapy.Field()
    area = scrapy.Field()
    reserve = scrapy.Field()
    price = scrapy.Field()
    remark = scrapy.Field()
    owner = scrapy.Field()
    entrydate = scrapy.Field()
    refertb = scrapy.Field()
    referi = scrapy.Field()
    parcel = scrapy.Field()

    date_datetime = scrapy.Field()
    saletype = scrapy.Field()
    proptype = scrapy.Field()
    reserve_int = scrapy.Field()
    type = scrapy.Field()
